#! /bin/bash
if [ -d $1 ]; then
	echo '';
	echo -e "\e[1;31m------------\e[0m"
	echo -e "\e[0;37mInstall Tool:\e[0m"
	echo -e "\e[1;31m--------------------------------------------------------------\e[0m"
	read INSTALL_QUERY
	QUIT="quit"
	if [ "$QUIT" = "$INSTALL_QUERY" ]; then
		exit
	else
		sudo apt install "$INSTALL_QUERY"
	fi
else
	echo -e "\e[1;31m----------\e[0m"
	echo -e "\e[0;37mInstalling:\e[0m"
	echo -e "\e[1;31m--------------------------------------------------------------\e[0m"
	sudo apt install $*
fi
#---------------------------------------------------------------------------
# Written By: Jaike Howard copyleft 2009
