#! /bin/bash

if [ -d $1 ]; then
	echo '';
	echo -e "\e[1;31m---------\e[0m"
	echo -e "\e[0;37mInfo Tool:\e[0m"
	echo -e "\e[1;31m--------------------------------------------------------------------------------\e[0m"
	read SEARCH_QUERY
	QUIT="quit"
	if [ "$QUIT" = "$SEARCH_QUERY" ]; then
		exit
	else
		cp show-apt.log last_show-apt.log
		sudo aptitude show "$SEARCH_QUERY" | egrep --color=always $\|'New|Automatically\ installed|Multi-Arch|Breaks|Homepage|Description|PreDepends|Depends|Provides|Replaces|Recommends|Conflicts|Suggests|Uncompressed\ Size|Architecture|Maintainer|Section|Priority|Version|State|Package' > show-apt.log
		more show-apt.log
	fi
else
	echo -e "\e[1;31m----------------\e[0m"
	echo -e "\e[0;37m$1 Info:\e[0m"
	echo -e "\e[1;31m--------------------------------------------------------------------------------\e[0m"
	cp show-apt.log last_show-apt.log
	sudo aptitude show "$1" | egrep --color=always $\|'New|Automatically\ installed|Multi-Arch|Breaks|Homepage|Description|PreDepends|Depends|Provides|Replaces|Recommends|Conflicts|Suggests|Uncompressed\ Size|Architecture|Maintainer|Section|Priority|Version|State|Package' > show-apt.log
	more show-apt.log
	exit
fi

#-------------------------------------------------------------------------------
# Written By: Jaike Howard copyleft 2009
